version: '4'

services: 

  hadoop-echo:
    image: drhazem95/hadooppsudoubt:v1.1
    container_name: hazem-hadoop
    hostname: hadoop-db
    restart: always
    volumes:
     - ./Data:/uer/local/Data 
     - ./MapReduce:/usr/local/Python
    